"""
@author Maksim Selivanov
Module contains functions for generating data from template. 
"""

from random import randint
from random import seed
from uuid import uuid4
from string import ascii_letters


def _random_char_sequence(num_of_symbols, char_base):
    """
    Returns string of random characters with a length of num_of_symbols from char_base
    """
    seed()
    seq_len = len(char_base)
    return ''.join([char_base[randint(0, seq_len-1)] for _ in range(num_of_symbols)])

def random_int(start, end):
    """
    Function generates random integer N such as start<=N<=end 
    """    
    seed()
    return randint(start, end)

def choose_element(element_list):
    """
    Function returns random element from the list
    """
    return element_list[random_int(0, len(element_list)-1)]
    
    
def alpha(num_of_symbols):
    """
    Returns string of random characters with a length of num_of_symbols
    """
    return _random_char_sequence(num_of_symbols, ascii_letters)


def array(num_elements, element_func, *element_func_args):
    """
    Returns array of elements with a length of num_elements.
    Every element is generated by a call to element_func(*element_func_args).
    """
    return [element_func(*element_func_args) for _ in range(num_elements)]    

def random_uuid_string():    
    """
    Generates random UUID and returns it as a hex string: '12345678-1234-5678-1234-567812345678'
    """
    return str(uuid4())